window:
  padding:
    x: 0
    y: 0
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

font:
  normal: &font-normal
    # family: "Hack Nerd Font"
    # family: Menlo
    # family: "Cousine Nerd Font"
    # family: "CodeNewRoman Nerd Font"
    # family: "CodeNewRoman Nerd Font Mono"
    # family: "CodeNewRoman Nerd Font Propo"
    # family: "Cousine Nerd Font"
    # family: "Cousine Nerd Font Mono"
    # family: "Cousine Nerd Font Propo"
    # family: "FiraCode Nerd Font"
    # family: "FiraCode Nerd Font Med"
    # family: "FiraCode Nerd Font Mono"
    # family: "FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Light"
    # family: "FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Med"
    # family: "FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Ret"
    # family: "FiraCode Nerd Font Mono,FiraCode Nerd Font Mono SemBd"
    # family: "FiraCode Nerd Font Propo"
    # family: "FiraCode Nerd Font Propo Ret"
    # family: "FiraCode Nerd Font Propo,FiraCode Nerd Font Propo Light"
    # family: "FiraCode Nerd Font Propo,FiraCode Nerd Font Propo Med"
    # family: "FiraCode Nerd Font Propo,FiraCode Nerd Font Propo SemBd"
    # family: "FiraCode Nerd Font,FiraCode Nerd Font Light"
    # family: "FiraCode Nerd Font,FiraCode Nerd Font Ret"
    # family: "FiraCode Nerd Font,FiraCode Nerd Font SemBd"
    # family: "FiraMono Nerd Font"
    # family: "FiraMono Nerd Font Mono"
    # family: "FiraMono Nerd Font Mono Medium"
    # family: "FiraMono Nerd Font Propo"
    # family: "FiraMono Nerd Font Propo,FiraMono Nerd Font Propo Medium"
    # family: "FiraMono Nerd Font"
    # family: "FiraMono Nerd Font Medium"
    # family: "Hack Nerd Font"
    family: "Hack Nerd Font Mono"
    # family: "Hack Nerd Font Propo"
    # family: monospace
    # family: Menlo
    style: Regular

  bold:
    <<: *font-normal
    # family: monospace
    # family: Hack Nerd Font
    style: Bold

  italic:
    <<: *font-normal
    # family: Hack Nerd Font
    # family: monospace
    # family: monospace
    style: Italic

  bold_italic:
    <<: *font-normal
    # family: Hack Nerd Font
    # family: monospace
    # family: monospace
    style: Bold Italic

  # normal:
  #   family: "Agave"
  size: 12
  # glyph_offset:
  #   y: 1

draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: false

import:
  # - ~/.catppuccin-frappe.yml
  - ~/.catppuccin-latte.yml
  # - ~/.catppuccin-macchiato.yml
  - ~/.catppuccin-mocha.yml

shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux"

key_bindings:
  - {
    key: Return,
    mods: Super|Shift,
    action: SpawnNewInstance
  }
