window:
  padding:
    x: 0
    y: 0
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

font:
  normal: &font-normal
    # You can find awailable fonts with `fc-listr`
    family: "Hack Nerd Font Mono"
    style: Regular
  bold:
    # <<: *font-normal
    style: Bold
  italic:
    # <<: *font-normal
    style: Italic
  bold_italic:
    # <<: *font-normal
    style: Bold Italic
  size: 12

env:
  TERM: xterm-256color

draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: false

# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x22272e'
    # foreground: '0x768390'
    # foreground: '0xaeb7bf'
    foreground: '0x95A2AF'

    dim_foreground: '0xeff0f1'
    bright_foreground: '0xffffff'
    dim_background: '0x31363b'
    bright_background: '0x000000'

  # Normal colors
  normal:
    black:   '0x545d68'
    red:     '0xf47067'
    green:   '0x57ab5a'
    yellow:  '0xc69026'
    blue:    '0x539bf5'
    magenta: '0xb083f0'
    cyan:    '0x39c5cf'
    white:   '0x909dab'

  # Bright colors
  bright:
    black:   '0x636e7b'
    red:     '0xff938a'
    green:   '0x6bc46d'
    yellow:  '0xdaaa3f'
    blue:    '0x6cb6ff'
    magenta: '0xdcbdfb'
    cyan:    '0x56d4dd'
    white:   '0xcdd9e5'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xff938a' }

# import:
#   # # Other interesting themes
#   - ~/.config/alacritty/themes/alacritty/themes/breeze.yaml
#   - ~/.config/alacritty/themes/alacritty/themes/github_dimmed.yaml
#   #
#   # - ~/.config/alacritty/themes/alacritty/themes/darcula.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/dracula.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/flat_remix.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/gnome_terminal.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/konsole_linux.yaml
#   #
#   # - ~/.config/alacritty/themes/alacritty/themes/omni.yaml
#   #
#   #
#   # - ~/.config/alacritty/themes/alacritty/themes/solarized_dark.yaml
#   #
#   # - ~/.config/alacritty/themes/alacritty/themes/tender.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/terminal_app.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/tomorrow_night_bright.yaml
#
#   #
#   # - ~/.config/alacritty/themes/alacritty/themes/Cobalt2.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/argonaut.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/blood_moon.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/monokai_charcoal.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/pencil_dark.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/rose-pine-moon.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/rose-pine.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/taerminal.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/tango_dark.yaml
#   # - ~/.config/alacritty/themes/alacritty/themes/thelovelace.yaml

shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux"

key_bindings:
  - {
    key: Return,
    mods: Super|Shift,
    action: SpawnNewInstance
  }
