
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xff938a"
index = 17

[colors.bright]
black = "0x636e7b"
blue = "0x6cb6ff"
cyan = "0x56d4dd"
green = "0x6bc46d"
magenta = "0xdcbdfb"
red = "0xff938a"
white = "0xcdd9e5"
yellow = "0xdaaa3f"

[colors.normal]
black = "0x545d68"
blue = "0x539bf5"
cyan = "0x39c5cf"
green = "0x57ab5a"
magenta = "0xb083f0"
red = "0xf47067"
white = "0x909dab"
yellow = "0xc69026"

[colors.primary]
background = "0x22272e"
# bright_background = "0x000000"
bright_foreground = "0xffffff"
# dim_background = "0x31363b"
dim_foreground = "0xeff0f1"
foreground = "0x95A2AF"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux"]

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0

[general]
import = [
    # "~/.config/alacritty/themes/themes/{theme}.toml"
    # "~/.config/alacritty/themes/themes/{theme}.toml"
    # "~/.config/alacritty/alacritty-theme/themes/Cobalt2.toml"
    # "~/.config/alacritty/alacritty-theme/themes/Mariana.toml"
    # "~/.config/alacritty/alacritty-theme/themes/afterglow.toml"
    # "~/.config/alacritty/alacritty-theme/themes/alabaster.toml"
    # "~/.config/alacritty/alacritty-theme/themes/alabaster_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/alacritty_0_12.toml"
    # "~/.config/alacritty/alacritty-theme/themes/argonaut.toml"
    # "~/.config/alacritty/alacritty-theme/themes/atom_one_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/ayu_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/baitong.toml"
    # "~/.config/alacritty/alacritty-theme/themes/base16_default_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/blood_moon.toml"
    # "~/.config/alacritty/alacritty-theme/themes/bluish.toml"
    # "~/.config/alacritty/alacritty-theme/themes/breeze.toml"
    # "~/.config/alacritty/alacritty-theme/themes/campbell.toml"
    # "~/.config/alacritty/alacritty-theme/themes/carbonfox.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin_frappe.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/alacritty-theme/themes/challenger_deep.toml"
    # "~/.config/alacritty/alacritty-theme/themes/citylights.toml"
    # "~/.config/alacritty/alacritty-theme/themes/cyber_punk_neon.toml"
    # "~/.config/alacritty/alacritty-theme/themes/darcula.toml"
    # "~/.config/alacritty/alacritty-theme/themes/dark_pastels.toml"
    # "~/.config/alacritty/alacritty-theme/themes/deep_space.toml"
    # "~/.config/alacritty/alacritty-theme/themes/doom_one.toml"
    # "~/.config/alacritty/alacritty-theme/themes/dracula.toml"
    # "~/.config/alacritty/alacritty-theme/themes/everforest_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/everforest_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/falcon.toml
    # "~/.config/alacritty/alacritty-theme/themes/flat_remix.toml"
    # "~/.config/alacritty/alacritty-theme/themes/flexoki.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark_colorblind.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark_default.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark_dimmed.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark_high_contrast.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_dark_tritanopia.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_light_colorblind.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_light_default.toml""
    # "~/.config/alacritty/alacritty-theme/themes/github_light_high_contrast.toml"
    # "~/.config/alacritty/alacritty-theme/themes/github_light_tritanopia.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gnome_terminal.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gotham.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_material.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_material_medium_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_material_medium_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/hardhacker.toml"
    # "~/.config/alacritty/alacritty-theme/themes/high_contrast.toml"
    # "~/.config/alacritty/alacritty-theme/themes/horizon-dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
    # "~/.config/alacritty/alacritty-theme/themes/inferno.toml"
    # "~/.config/alacritty/alacritty-theme/themes/iris.toml"
    # "~/.config/alacritty/alacritty-theme/themes/iterm.toml"
    # "~/.config/alacritty/alacritty-theme/themes/kanagawa_dragon.toml"
    # "~/.config/alacritty/alacritty-theme/themes/kanagawa_wave.toml"
    # "~/.config/alacritty/alacritty-theme/themes/konsole_linux.toml"
    # "~/.config/alacritty/alacritty-theme/themes/low_contrast.toml"
    # "~/.config/alacritty/alacritty-theme/themes/marine_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/material_theme.toml"
    # "~/.config/alacritty/alacritty-theme/themes/material_theme_mod.toml"
    # "~/.config/alacritty/alacritty-theme/themes/meliora.toml"
    # "~/.config/alacritty/alacritty-theme/themes/midnight-haze.toml"
    # "~/.config/alacritty/alacritty-theme/themes/monokai_charcoal.toml"
    # "~/.config/alacritty/alacritty-theme/themes/monokai_pro.toml"
    # "~/.config/alacritty/alacritty-theme/themes/moonlight_ii_vscode.toml"
    # "~/.config/alacritty/alacritty-theme/themes/msx.toml"
    # "~/.config/alacritty/alacritty-theme/themes/night_owlish_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/nightfox.toml"
    # "~/.config/alacritty/alacritty-theme/themes/noctis-lux.toml"
    # "~/.config/alacritty/alacritty-theme/themes/nord.toml"
    # "~/.config/alacritty/alacritty-theme/themes/nord_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/nordic.toml"
    # "~/.config/alacritty/alacritty-theme/themes/oceanic_next.toml"
    # "~/.config/alacritty/alacritty-theme/themes/omni.toml"
    # "~/.config/alacritty/alacritty-theme/themes/one_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/palenight.toml"
    # "~/.config/alacritty/alacritty-theme/themes/papercolor_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/papercolor_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/papertheme.toml"
    # "~/.config/alacritty/alacritty-theme/themes/pencil_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/pencil_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/rainbow.toml"
    # "~/.config/alacritty/alacritty-theme/themes/remedy_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/rose-pine-dawn.toml"
    # "~/.config/alacritty/alacritty-theme/themes/rose-pine-moon.toml"
    # "~/.config/alacritty/alacritty-theme/themes/rose-pine.toml"
    # "~/.config/alacritty/alacritty-theme/themes/seashells.toml"
    # "~/.config/alacritty/alacritty-theme/themes/smoooooth.toml"
    # "~/.config/alacritty/alacritty-theme/themes/snazzy.toml"
    # "~/.config/alacritty/alacritty-theme/themes/solarized_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/solarized_light.toml"
    # "~/.config/alacritty/alacritty-theme/themes/taerminal.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tango_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tender.toml"
    # "~/.config/alacritty/alacritty-theme/themes/terminal_app.toml"
    # "~/.config/alacritty/alacritty-theme/themes/thelovelace.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tokyo-night-storm.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tokyo-night.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night.toml",
    # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night_bright.toml",
    # "~/.config/alacritty/alacritty-theme/themes/ubuntu.toml"
    # "~/.config/alacritty/alacritty-theme/themes/wombat.toml"
    # "~/.config/alacritty/alacritty-theme/themes/xterm.toml"
    # "~/.config/alacritty/alacritty-theme/themes/zenburn.toml"
]

[terminal]

