window:
  padding:
    x: 0
    y: 0
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

font:
  normal: &font-normal
    # You can find awailable fonts with `fc-listr`
    family: "Hack Nerd Font Mono"
    style: Regular
  bold:
    # <<: *font-normal
    style: Bold
  italic:
    # <<: *font-normal
    style: Italic
  bold_italic:
    # <<: *font-normal
    style: Bold Italic
  size: 12

env:
  TERM: xterm-256color

draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: false

import:
  - ~/.config/alacritty/themes/alacritty/themes/github_dimmed.yaml
  # Other interesting themes
  # - ~/.config/alacritty/themes/alacritty/themes/Cobalt2.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/argonaut.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/blood_moon.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/breeze.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/darcula.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/dracula.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/flat_remix.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/gnome_terminal.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/konsole_linux.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/marine_dark.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/monokai_charcoal.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/nightfox.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/omni.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/papercolor_dark.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/pencil_dark.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/rose-pine-moon.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/rose-pine.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/solarized_dark.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/taerminal.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/tango_dark.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/tender.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/terminal_app.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/thelovelace.yaml
  # - ~/.config/alacritty/themes/alacritty/themes/tomorrow_night_bright.yaml

shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux"

key_bindings:
  - {
    key: Return,
    mods: Super|Shift,
    action: SpawnNewInstance
  }
