#! /usr/bin/env bash

# brew tap dbcli/tap
# brew install pgcli
brew tap nats-io/nats-tools
INSTALLED=`brew list`
APPLICATIONS=(
  nats-io/nats-tools/nats
  nats-io/nats-tools/nsc
  nats-server
)

apps_to_install=()
for app in ${APPLICATIONS[@]}; do
  # Checking that $app was installed by homebrew
  echo $INSTALLED | grep -q $app
  if [ $? != 0 ]; then
    apps_to_install+=("${app}")
  fi
done

if [ ${#apps_to_install[@]} -eq 0 ]; then
  echo "Nothing to install"
  exit 0
fi

# Installing fonts see
# https://gist.github.com/davidteren/898f2dcccd42d9f8680ec69a3a5d350e
brew tap homebrew/cask-fonts && brew install --cask font-hack-nerd-font

missing_apps=${apps_to_install[@]}
echo Installing ${missing_apps}
brew install ${missing_apps}
