#! /usr/bin/env bash

# brew tap dbcli/tap
# brew install pgcli

INSTALLED=`brew list`
APPLICATIONS=(
  kubectx
  font-hack-nerd-font
  atom
  bazel
  bzip2
  colordiff
  ctags
  kap
  kube-linter
  dbeaver-community
  diff-so-fancy
  displayplacer
  docker
  ffmpeg
  fzf
  git
  htop
  jq
  kubectl
  lazygit
  neovim
  nvm
  obs
  postgresql
  pyenv
  pyenv-virtualenv
  ripgrep
  subversion
  tig
  tmux
  urlview
  visual-studio-code
  youtube-dl
  zlib
  zsh
)
apps_to_install=()
for app in ${APPLICATIONS[@]}; do
  # Checking that $app was installed by homebrew
  echo $INSTALLED | grep -q $app
  if [ $? != 0 ]; then
    apps_to_install+=("${app}")
  fi
done

if [ ${#apps_to_install[@]} -eq 0 ]; then
  echo "Nothing to install"
  exit 0
fi

missing_apps=${apps_to_install[@]}
echo Installing ${missing_apps}
brew install ${missing_apps}
