#!/usr/bin/env zsh
#
# Update the dotfiles and all submodules in one command.
#
git pull origin master
git submodule init
git submodule update
git submodule foreach git checkout master
git submodule foreach git pull origin
git status
