#!/usr/bin/env bash

which -s brew
if [[ $? == 0 ]]; then

  which -s dotnet >> /dev/null
  if [[ $? != 0 ]]; then
    echo Installing dotnet
    brew install dotnet
  fi

  which -s mono >> /dev/null
  if [[ $? != 0 ]]; then
    echo Installing mono
    brew install mono
  fi

  # https://github.com/OmniSharp/homebrew-omnisharp-roslyn
  brew tap | grep -q omnisharp-roslyn
  if [[ $? != 0 ]]; then
    echo Adding the missing omnisharp-roslyn tab
    brew tap omnisharp/omnisharp-roslyn
  fi
  brew list | grep -q omnisharp-mono
  if [[ $? != 0 ]]; then
    echo Installing omnisharp-mono
    brew install omnisharp-mono
  fi
fi
